/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface NwAccordion {
        "color": string;
        "description": string;
        "label": string;
        "width": string;
    }
}
declare global {
    interface HTMLNwAccordionElement extends Components.NwAccordion, HTMLStencilElement {
    }
    var HTMLNwAccordionElement: {
        prototype: HTMLNwAccordionElement;
        new (): HTMLNwAccordionElement;
    };
    interface HTMLElementTagNameMap {
        "nw-accordion": HTMLNwAccordionElement;
    }
}
declare namespace LocalJSX {
    interface NwAccordion {
        "color"?: string;
        "description"?: string;
        "label"?: string;
        "onOnToggle"?: (event: CustomEvent<any>) => void;
        "width"?: string;
    }
    interface IntrinsicElements {
        "nw-accordion": NwAccordion;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "nw-accordion": LocalJSX.NwAccordion & JSXBase.HTMLAttributes<HTMLNwAccordionElement>;
        }
    }
}
